### ISSUE TITLE
build scripts

### ISSUE THREAD

**Issue by mattyjones** [BlackArch/blackarch-guide#1]
Any reason you have several shell scripts for building. I would think it would be eaiser to stream this all with make?

Also any reason you don't have this hooked into TravisCI? Do you use some other CI pipeline?

I would be willing to handle the TravisCI and make stuff if you would accept the pr.

**Comment by noptrix** [comment]
In progress as well.

**Comment by mattyjones** [comment]
Sweet. I am fixing a few small typo's in the guide and some latex cruft as well. I added a vagrantbox to the repo so that I can build/test without having everything installed and can push that up as well for others.

Let me know if you guys would like any help on the make front concerning docs.

**Comment by noptrix** [comment]
That's awesome. Thanks a lot!
