### ISSUE TITLE
Turkish PDF char problem 

### ISSUE THREAD

**Issue by thunderbirdtr** [BlackArch/blackarch-guide#11]
Hello, I just read the Turkish translate of Black Arch and I compare with latex file and seems to be PDF didn't contain turkish special char such as (ş,ç,ğ,ü,i,I,ö) so It need to re-generate from Latex file.

Thank you 

Link : https://blackarch.org/blackarch-guide-tr.pdf

**Comment by noptrix** [comment]
fixed
