### ISSUE TITLE
color scheme

### ISSUE THREAD

**Issue by mattyjones** [BlackArch/blackarch-guide#2]
I am all for brand cohesion and I like the black/red/white but for documentation I think something more neutral should be adopted, at least in the pdf version after the title pages.

At some point as the guide grows it will get tough on the eyes to read it and also syntax highlighting would be nice in the proposed examples sections and that will look off with all the darkness. 

Maybe some kind of neutral grey with black writing would be nice, it will still keep it looking not like a traditional book but will also be much eaiser on the eyes for prolonged reading.

**Comment by noptrix** [comment]
Yep. Tbh, we thought the same. We will change it soon. Thanks!

**Comment by noptrix** [comment]
changed
