### ISSUE TITLE
Did anybody contact with you about the Chinese version guide?

### ISSUE THREAD

**Issue by WayneDevMaze** [BlackArch/blackarch-guide#32]
Hey there,
I am a graduate student, in Guangzhou University. My major is program&network security. I'm willing to translate guide to Chinese.
I wanna to know that, has anyone translated it to Chinese?

Hope to get your reply.

From Tao

**Comment by ikstream** [comment]
If you check the source files in this repo you will see, that there is a tex file for Chinese translation. How far it is translated and how precise i can't tell. 
My current guess would be, that it does not build, so that it is not available on our server.

**Comment by noraj** [comment]
@WayneDevMaze see https://github.com/BlackArch/blackarch-guide/blob/master/latex/blackarch-guide-zh.tex
