### ISSUE TITLE
it's an old issue... 

### ISSUE THREAD

**Issue by CS13337** [BlackArch/blackarch-guide#46]
current blackarch installs compile / fail if your python is 3.8 and not python3.7

 running "sudo blackman -a" or "sudo blackman -g blackarch-forensics"
produced oodles of the same error message in regards to line 178 from /usr/lib/python3.8/site-packages file=sys.stderr

infact for each and every package it burped out that same error

yup my python was to new for the install...

in my case this was in my .bashrc file: 

export PYTHONPATH=${PYTHONPATH}:"/usr/lib/python3.8/:/usr/lib/python3.8/site-packages/"

me being simple, comment out the line, duplicated the line as follows:

export PYTHONPATH=${PYTHONPATH}:"/usr/lib/python3.7/:/usr/lib/python3.7/site-packages/"

after opening  new terminal and running the command to install again, all was well in the boxen verse.

as i'm new here and only complaining cuz i can, i though i would help out instead. 

solution
insert one line somewhere near the top of the install guide / website mentioning the python version requirement

CS13337

**Comment by noraj** [comment]
@CS13337 Rather than updating the doc, I think it would be better to update the tool https://github.com/BlackArch/blackman

**Comment by CS13337** [comment]
you know that's a great idea.

thank you



Blah Blah Blah says the iPhone

On Jun 24, 2020, at 7:36 AM, Alexandre ZANNI <notifications@github.com> wrote:

@CS13337 Rather than updating the doc, I think it would be better to update the tool https://github.com/BlackArch/blackman

**Comment by aancw** [comment]
But, I don't see `python` in Blackman source code. Which one is causing the problem?

@noraj I think it's because of some tools in group that not yet compatible with python 3.8
