### ISSUE TITLE
Bug in installation guide for users

### ISSUE THREAD

**Issue by All3xJ** [BlackArch/blackarch-guide#48]
It's writtent to write

`sudo ./strap.sh`

but it says command not found.

So instead, it should be:

`sudo sh ./strap.sh`

and it works :)

**Comment by anunna** [comment]
It is not an issue with the script. The instructions states that you must make the script executable.

`sudo chmod +x strap.sh`

then

`sudo ./strap.sh`

**Comment by anunna** [comment]
I see now what you mean, the pdf guide is missing that step.
