### ISSUE TITLE
aarch64 multilib package 404 error

### ISSUE THREAD

**Issue by AgentBuzz** [BlackArch/blackarch-guide#49]
Raspberry Pi 4 (8gb)
Arch Linux (AArch64)

Following the steps as directed in the [installation guide](https://blackarch.org/downloads.html#blackarch-arm) to install on top of an existing Arch installation.

This step

>  Enable multilib following [https://wiki.archlinux.org/index.php/Official_repositories#Enabling_multilib](https://wiki.archlinux.org/index.php/Official_repositories#Enabling_multilib) and run:
>$ sudo pacman -Syu

(side note there is no multilib entry to uncomment in /etc/pacman.conf)

results in an error stating 

> error: failed retrieving file 'multilib.db' from mirror.archlinuxarm.org : The requested URL returned error: 404

[It would appear that the multilib package is unsupported in the aarch64 build(s)
](https://www.reddit.com/r/archlinuxarm/comments/il2fgr/cannot_install_32bit_library_using_multilib/)

**Comment by anunna** [comment]
Aarch64 only supports 64bit packages, therefore ArchLinux ARM does not ship with multilib configuration in pacman.conf

The guide only includes the basic steps to add the repository and does not cover issues on hardware compatibility. It would be the responsibility of the user to understand their hardware and/or limitations thereof.

**Comment by AgentBuzz** [comment]
> 
> 
> Aarch64 only supports 64bit packages, therefore ArchLinux ARM does not ship with multilib configuration in pacman.conf
> 
> The guide only includes the basic steps to add the repository and does not cover issues on hardware compatibility. It would be the responsibility of the user to understand their hardware and/or limitations thereof.

This should be clarified on the website.

>BlackArch is compatible with Arch Linux ARM. It effectively supports all of the Aarch64 platforms listed [here](http://archlinuxarm.org/platforms).

The way **this** is worded gives the impression that it would be supported. Especially since the following statement directs the user to follow the installation steps without mentioning it wont be fully supported.

> In order to install BlackArch on an ARM platform, follow the install instructions for your device on [archlinuxarm.org](http://archlinuxarm.org/) and install BlackArch [as an unofficial user repository](https://blackarch.org/downloads.html#install-repo). Soon we will release adaptations of the Arch Linux ARM images with BlackArch packages pre-installed.

**Comment by ikstream** [comment]
It does not state, that it fully supports each and every tool. This should be done common sense, that not every tool works on arm.

Never the less we can add a statement, that not all tools will be available for arm

**Comment by AgentBuzz** [comment]
> 
> 
> It does not state, that it fully supports each and every tool. This should be done common sense, that not every tool works on arm.
> 
> Never the less we can add a statement, that not all tools will be available for arm

It is for the aarch64 build not archarm. The install guide also confuses these two builds interchanging the two as if they are the exact same.

**Comment by anunna** [comment]
ARMv8, which is what your Raspberry Pi 4 has, is named "aarch64". ARM is the semiconductor company that makes the "aarch64"processor.

Ref: https://en.m.wikipedia.org/wiki/ARM_architecture
